kind: Service
apiVersion: v1
metadata:
  name: util-service
  namespace: prod
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: utility-deployment
  type: LoadBalancer
  sessionAffinity: ClientIPs